tdd/config/routes.rb
Vchatter::Application.routes.draw do

  resources :deletion_feedbacks

  get "home/index"


  ### Two routes defined for accout settings and update actions 
  get "profile/account_settings"
  match 'profile/account_update' => 'profile#account_update', :via => :put

  get "profile/basic_information"
  put "profile/basic_information"
  
  get "profile/activities"
  match 'profile/activities_update' => 'profile#activities_update', :via => :put
  
  
  match "profile/password_update", :via=>:post
  
  get "profile/relationships"
  match 'profile/relationships_update' => 'profile#relationships_update', :via => :put

  get "profile/image"
  match 'profile/image_update' => 'profile#image_update', :via => :post

  get "profile/interests"
  match 'profile/interests_update' => 'profile#interests_update', :via => :put

  get "profile/philosophy"
  match 'profile/philosophy_update' => 'profile#philosophy_update', :via => :put

  get "profile/contact_information"
  #get "profile/contact_information/:id" => "profile#contact_information"
  match 'profile/contact_information_update' => 'profile#contact_information_update', :via => :put

  match 'profile/deactiviate_account' => 'profile#deactiviate_account', :via => :post

  get "vanities/check_availability"


  
  resources :notification_preferences
  resources :notification_types
  resources :notification_subscriptions
  resources :notifications

  # welcome controller= standard web stuff content
  get "welcome/index"  # the 'home page

  get "welcome/about_us"
  get "welcome/jobs"
  get "welcome/fans"
  get "welcome/twitter"
  get "welcome/facebook"
  get "welcome/press"
  get "welcome/terms"
  get "welcome/privacy"
  get "welcome/help"
  get "welcome/quickstart_guide"
  get "welcome/tips"
  get "welcome/community_guidelines"
  get "welcome/contact_us"

  resources :groups do
    member do
      post :update_count
    end
    collection do
      get :most_popular
      get :most_recent
      get :recommended
    end
  end

  resource :welcome

  devise_for :users, :controllers => {:registrations => 'registrations', 
                                      :sessions=>'sessions',
                                      :omniauth_callbacks => "users/omniauth_callbacks"} do
      post "registrations/step_2" => "registrations#step_2"
      post "registrations/step_3" => "registrations#step_3"
       
  end

  resources :follows

  resources :users do
      resources :follows
      resources :followers
      member do
        get :locate
      end
      
  end
  
  
  
  # resources :users do
  #     resources :groups
  # end
   
  resources :authentications
  resource :photo
  
  get "photo/new_photo_form"
  get "photo/new_photo_iframe"
  post "photo/set_image"

  root :controller => :welcome, :action => 'index'
  
  #this route should be last as it checks for the vanity urls
  get '/:vanity_name', :controller => 'vanities', :action => 'show'
  
  
end

tdd/app/models/deletion_feedback.rb
class DeletionFeedback < ActiveRecord::Base
end

tdd/app/controllers/deletion_feedbacks_controller.rb
class DeletionFeedbacksController < ApplicationController
  # GET /deletion_feedbacks
  # GET /deletion_feedbacks.xml
  def index
    @deletion_feedbacks = DeletionFeedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @deletion_feedbacks }
    end
  end

  # GET /deletion_feedbacks/1
  # GET /deletion_feedbacks/1.xml
  def show
    @deletion_feedback = DeletionFeedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deletion_feedback }
    end
  end

  # GET /deletion_feedbacks/new
  # GET /deletion_feedbacks/new.xml
  def new
    @deletion_feedback = DeletionFeedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deletion_feedback }
    end
  end

  # GET /deletion_feedbacks/1/edit
  def edit
    @deletion_feedback = DeletionFeedback.find(params[:id])
  end

  # POST /deletion_feedbacks
  # POST /deletion_feedbacks.xml
  def create
    @deletion_feedback = DeletionFeedback.new(params[:deletion_feedback])

    respond_to do |format|
      if @deletion_feedback.save
        format.html { redirect_to(@deletion_feedback, :notice => 'Deletion feedback was successfully created.') }
        format.xml  { render :xml => @deletion_feedback, :status => :created, :location => @deletion_feedback }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @deletion_feedback.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deletion_feedbacks/1
  # PUT /deletion_feedbacks/1.xml
  def update
    @deletion_feedback = DeletionFeedback.find(params[:id])

    respond_to do |format|
      if @deletion_feedback.update_attributes(params[:deletion_feedback])
        format.html { redirect_to(@deletion_feedback, :notice => 'Deletion feedback was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deletion_feedback.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deletion_feedbacks/1
  # DELETE /deletion_feedbacks/1.xml
  def destroy
    @deletion_feedback = DeletionFeedback.find(params[:id])
    @deletion_feedback.destroy

    respond_to do |format|
      format.html { redirect_to(deletion_feedbacks_url) }
      format.xml  { head :ok }
    end
  end
end

tdd/app/helpers/deletion_feedbacks_helper.rb
module DeletionFeedbacksHelper
end

tdd/app/views/deletion_feedbacks/_form.html.erb
<%= form_for(@deletion_feedback) do |f| %>
  <% if @deletion_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deletion_feedback.errors.count, "error") %> prohibited this deletion_feedback from being saved:</h2>

      <ul>
      <% @deletion_feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tdd/app/views/deletion_feedbacks/edit.html.erb
<h1>Editing deletion_feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @deletion_feedback %> |
<%= link_to 'Back', deletion_feedbacks_path %>

tdd/app/views/deletion_feedbacks/index.html.erb
<h1>Listing deletion_feedbacks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deletion_feedbacks.each do |deletion_feedback| %>
  <tr>
    <td><%= link_to 'Show', deletion_feedback %></td>
    <td><%= link_to 'Edit', edit_deletion_feedback_path(deletion_feedback) %></td>
    <td><%= link_to 'Destroy', deletion_feedback, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deletion feedback', new_deletion_feedback_path %>

tdd/app/views/deletion_feedbacks/new.html.erb
<h1>New deletion_feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', deletion_feedbacks_path %>

tdd/app/views/deletion_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_deletion_feedback_path(@deletion_feedback) %> |
<%= link_to 'Back', deletion_feedbacks_path %>