tdd/config/routes.rb
Vchatter::Application.routes.draw do

  resources :deletion_feedbacks

  get "home/index"


  ### Two routes defined for accout settings and update actions 
  get "profile/account_settings"
  match 'profile/account_update' => 'profile#account_update', :via => :put

  get "profile/basic_information"
  put "profile/basic_information"
  
  get "profile/activities"
  match 'profile/activities_update' => 'profile#activities_update', :via => :put
  
  
  match "profile/password_update", :via=>:post
  
  get "profile/relationships"
  match 'profile/relationships_update' => 'profile#relationships_update', :via => :put

  get "profile/image"
  match 'profile/image_update' => 'profile#image_update', :via => :post

  get "profile/interests"
  match 'profile/interests_update' => 'profile#interests_update', :via => :put

  get "profile/philosophy"
  match 'profile/philosophy_update' => 'profile#philosophy_update', :via => :put

  get "profile/contact_information"
  #get "profile/contact_information/:id" => "profile#contact_information"
  match 'profile/contact_information_update' => 'profile#contact_information_update', :via => :put

  match 'profile/deactiviate_account' => 'profile#deactiviate_account', :via => :post

  get "vanities/check_availability"


  
  resources :notification_preferences
  resources :notification_types
  resources :notification_subscriptions
  resources :notifications

  # welcome controller= standard web stuff content
  get "welcome/index"  # the 'home page

  get "welcome/about_us"
  get "welcome/jobs"
  get "welcome/fans"
  get "welcome/twitter"
  get "welcome/facebook"
  get "welcome/press"
  get "welcome/terms"
  get "welcome/privacy"
  get "welcome/help"
  get "welcome/quickstart_guide"
  get "welcome/tips"
  get "welcome/community_guidelines"
  get "welcome/contact_us"

  resources :groups do
    member do
      post :update_count
    end
    collection do
      get :most_popular
      get :most_recent
      get :recommended
    end
  end

  resource :welcome

  devise_for :users, :controllers => {:registrations => 'registrations', 
                                      :sessions=>'sessions',
                                      :omniauth_callbacks => "users/omniauth_callbacks"} do
      post "registrations/step_2" => "registrations#step_2"
      post "registrations/step_3" => "registrations#step_3"
       
  end

  resources :follows

  resources :users do
      resources :follows
      resources :followers
      member do
        get :locate
      end
      
  end
  
  
  
  # resources :users do
  #     resources :groups
  # end
   
  resources :authentications
  resource :photo
  
  get "photo/new_photo_form"
  get "photo/new_photo_iframe"
  post "photo/set_image"

  root :controller => :welcome, :action => 'index'
  
  #this route should be last as it checks for the vanity urls
  get '/:vanity_name', :controller => 'vanities', :action => 'show'
  
  
end

tdd/app/models/notification.rb
class Notification < ActiveRecord::Base
  # stores any actual notifications for a group
  
  

  belongs_to :notification_type  # what type of notification is it
  belongs_to :group # wht group does it belong to

  
end

tdd/app/models/notification_type.rb
class NotificationType < ActiveRecord::Base
  #  attr_accessible :name, :description
  has_many :notification_subscriptions
  has_many :notifications


  # short cut methods to spit out codes 
    def code_for_follower_join
        code=NotificationType.find_by_name("New follower joins group")
        return code.id
    end
    
    def code_for_follower_message_send
          code=NotificationType.find_by_name("Follower sends message to a group")
          return code.id
    end
    
    def code_for_follower_flagged
          code=NotificationType.find_by_name("Followeris flagged")
          return code.id
    end

    
    def code_for_private_message_received
          code=NotificationType.find_by_name("Received private message")
          return code.id
    end


end

tdd/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(params[:notification])
    if @notification.save
      redirect_to @notification, :notice => "Successfully created notification."
    else
      render :action => 'new'
    end
  end

  def edit
    @notification = Notification.find(params[:id])
  end

  def update
    @notification = Notification.find(params[:id])
    if @notification.update_attributes(params[:notification])
      redirect_to @notification, :notice  => "Successfully updated notification."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_to notifications_url, :notice => "Successfully destroyed notification."
  end
end

tdd/app/helpers/notifications_helper.rb
module NotificationsHelper
end

tdd/app/views/notifications/_form.html.erb
<%= form_for @notification do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </p>
  <p>
    <%= f.label :notification_type_id %><br />
    <%= f.text_field :notification_type_id %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p><%= f.submit %></p>
<% end %>

tdd/app/views/notifications/edit.html.erb
<% "Edit Notification" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @notification %> |
  <%= link_to "View All", notifications_path %>
</p>

tdd/app/views/notifications/index.html.erb
<% "Notifications" %>

<table>
  <tr>
    <th>Group</th>
    <th>Notification Type</th>
    <th>Body</th>
  </tr>
  <% for notification in @notifications %>
    <tr>
      <td><%= notification.group_id %></td>
      <td><%= notification.notification_type_id %></td>
      <td><%= notification.body %></td>
      <td><%= link_to "Show", notification %></td>
      <td><%= link_to "Edit", edit_notification_path(notification) %></td>
      <td><%= link_to "Destroy", notification, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Notification", new_notification_path %></p>

tdd/app/views/notifications/new.html.erb
<% "New Notification" %>

<%= render 'form' %>

<p><%= link_to "Back to List", notifications_path %></p>

tdd/app/views/notifications/show.html.erb
<% "Notification" %>

<p>
  <strong>Group:</strong>
  <%= @notification.group_id %>
</p>
<p>
  <strong>Notification Type:</strong>
  <%= @notification.notification_type_id %>
</p>
<p>
  <strong>Body:</strong>
  <%= @notification.body %>
</p>

<p>
  <%= link_to "Edit", edit_notification_path(@notification) %> |
  <%= link_to "Destroy", @notification, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", notifications_path %>
</p>