tdd/config/routes.rb
Vchatter::Application.routes.draw do

  resources :deletion_feedbacks

  get "home/index"


  ### Two routes defined for accout settings and update actions 
  get "profile/account_settings"
  match 'profile/account_update' => 'profile#account_update', :via => :put

  get "profile/basic_information"
  put "profile/basic_information"
  
  get "profile/activities"
  match 'profile/activities_update' => 'profile#activities_update', :via => :put
  
  
  match "profile/password_update", :via=>:post
  
  get "profile/relationships"
  match 'profile/relationships_update' => 'profile#relationships_update', :via => :put

  get "profile/image"
  match 'profile/image_update' => 'profile#image_update', :via => :post

  get "profile/interests"
  match 'profile/interests_update' => 'profile#interests_update', :via => :put

  get "profile/philosophy"
  match 'profile/philosophy_update' => 'profile#philosophy_update', :via => :put

  get "profile/contact_information"
  #get "profile/contact_information/:id" => "profile#contact_information"
  match 'profile/contact_information_update' => 'profile#contact_information_update', :via => :put

  match 'profile/deactiviate_account' => 'profile#deactiviate_account', :via => :post

  get "vanities/check_availability"


  
  resources :notification_preferences
  resources :notification_types
  resources :notification_subscriptions
  resources :notifications

  # welcome controller= standard web stuff content
  get "welcome/index"  # the 'home page

  get "welcome/about_us"
  get "welcome/jobs"
  get "welcome/fans"
  get "welcome/twitter"
  get "welcome/facebook"
  get "welcome/press"
  get "welcome/terms"
  get "welcome/privacy"
  get "welcome/help"
  get "welcome/quickstart_guide"
  get "welcome/tips"
  get "welcome/community_guidelines"
  get "welcome/contact_us"

  resources :groups do
    member do
      post :update_count
    end
    collection do
      get :most_popular
      get :most_recent
      get :recommended
    end
  end

  resource :welcome

  devise_for :users, :controllers => {:registrations => 'registrations', 
                                      :sessions=>'sessions',
                                      :omniauth_callbacks => "users/omniauth_callbacks"} do
      post "registrations/step_2" => "registrations#step_2"
      post "registrations/step_3" => "registrations#step_3"
       
  end

  resources :follows

  resources :users do
      resources :follows
      resources :followers
      member do
        get :locate
      end
      
  end
  
  
  
  # resources :users do
  #     resources :groups
  # end
   
  resources :authentications
  resource :photo
  
  get "photo/new_photo_form"
  get "photo/new_photo_iframe"
  post "photo/set_image"

  root :controller => :welcome, :action => 'index'
  
  #this route should be last as it checks for the vanity urls
  get '/:vanity_name', :controller => 'vanities', :action => 'show'
  
  
end

tdd/app/models/notification_subscription.rb
class NotificationSubscription < ActiveRecord::Base
  #  attr_accessible :group_id, :user_id, :notification_type_id
  belongs_to :user
  belongs_to :notification_type
  belongs_to :group


  
end

tdd/app/controllers/notification_subscriptions_controller.rb
class NotificationSubscriptionsController < ApplicationController
  def index
    @notification_subscriptions = NotificationSubscription.all
  end

  def show
    @notification_subscription = NotificationSubscription.find(params[:id])
  end

  def new
    @notification_subscription = NotificationSubscription.new
  end

  def create
    @notification_subscription = NotificationSubscription.new(params[:notification_subscription])
    if @notification_subscription.save
      redirect_to @notification_subscription, :notice => "Successfully created notification subscription."
    else
      render :action => 'new'
    end
  end

  def edit
    @notification_subscription = NotificationSubscription.find(params[:id])
  end

  def update
    @notification_subscription = NotificationSubscription.find(params[:id])
    if @notification_subscription.update_attributes(params[:notification_subscription])
      redirect_to @notification_subscription, :notice  => "Successfully updated notification subscription."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @notification_subscription = NotificationSubscription.find(params[:id])
    @notification_subscription.destroy
    redirect_to notification_subscriptions_url, :notice => "Successfully destroyed notification subscription."
  end
end

tdd/app/helpers/notification_subscriptions_helper.rb
module NotificationSubscriptionsHelper
end

tdd/app/views/notification_subscriptions/_form.html.erb
<%= form_for @notification_subscription do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :notification_type_id %><br />
    <%= f.text_field :notification_type_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

tdd/app/views/notification_subscriptions/edit.html.erb
<% "Edit Notification Subscription" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @notification_subscription %> |
  <%= link_to "View All", notification_subscriptions_path %>
</p>

tdd/app/views/notification_subscriptions/index.html.erb
<% "Notification Subscriptions" %>

<table>
  <tr>
    <th>Group</th>
    <th>User</th>
    <th>Notification Type</th>
  </tr>
  <% for notification_subscription in @notification_subscriptions %>
    <tr>
      <td><%= notification_subscription.group_id %></td>
      <td><%= notification_subscription.user_id %></td>
      <td><%= notification_subscription.notification_type_id %></td>
      <td><%= link_to "Show", notification_subscription %></td>
      <td><%= link_to "Edit", edit_notification_subscription_path(notification_subscription) %></td>
      <td><%= link_to "Destroy", notification_subscription, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Notification Subscription", new_notification_subscription_path %></p>

tdd/app/views/notification_subscriptions/new.html.erb
<% "New Notification Subscription" %>

<%= render 'form' %>

<p><%= link_to "Back to List", notification_subscriptions_path %></p>

tdd/app/views/notification_subscriptions/show.html.erb
<% "Notification Subscription" %>

<p>
  <strong>Group:</strong>
  <%= @notification_subscription.group_id %>
</p>
<p>
  <strong>User:</strong>
  <%= @notification_subscription.user_id %>
</p>
<p>
  <strong>Notification Type:</strong>
  <%= @notification_subscription.notification_type_id %>
</p>

<p>
  <%= link_to "Edit", edit_notification_subscription_path(@notification_subscription) %> |
  <%= link_to "Destroy", @notification_subscription, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", notification_subscriptions_path %>
</p>