tdd/config/routes.rb
Vchatter::Application.routes.draw do

  resources :deletion_feedbacks

  get "home/index"


  ### Two routes defined for accout settings and update actions 
  get "profile/account_settings"
  match 'profile/account_update' => 'profile#account_update', :via => :put

  get "profile/basic_information"
  put "profile/basic_information"
  
  get "profile/activities"
  match 'profile/activities_update' => 'profile#activities_update', :via => :put
  
  
  match "profile/password_update", :via=>:post
  
  get "profile/relationships"
  match 'profile/relationships_update' => 'profile#relationships_update', :via => :put

  get "profile/image"
  match 'profile/image_update' => 'profile#image_update', :via => :post

  get "profile/interests"
  match 'profile/interests_update' => 'profile#interests_update', :via => :put

  get "profile/philosophy"
  match 'profile/philosophy_update' => 'profile#philosophy_update', :via => :put

  get "profile/contact_information"
  #get "profile/contact_information/:id" => "profile#contact_information"
  match 'profile/contact_information_update' => 'profile#contact_information_update', :via => :put

  match 'profile/deactiviate_account' => 'profile#deactiviate_account', :via => :post

  get "vanities/check_availability"


  
  resources :notification_preferences
  resources :notification_types
  resources :notification_subscriptions
  resources :notifications

  # welcome controller= standard web stuff content
  get "welcome/index"  # the 'home page

  get "welcome/about_us"
  get "welcome/jobs"
  get "welcome/fans"
  get "welcome/twitter"
  get "welcome/facebook"
  get "welcome/press"
  get "welcome/terms"
  get "welcome/privacy"
  get "welcome/help"
  get "welcome/quickstart_guide"
  get "welcome/tips"
  get "welcome/community_guidelines"
  get "welcome/contact_us"

  resources :groups do
    member do
      post :update_count
    end
    collection do
      get :most_popular
      get :most_recent
      get :recommended
    end
  end

  resource :welcome

  devise_for :users, :controllers => {:registrations => 'registrations', 
                                      :sessions=>'sessions',
                                      :omniauth_callbacks => "users/omniauth_callbacks"} do
      post "registrations/step_2" => "registrations#step_2"
      post "registrations/step_3" => "registrations#step_3"
       
  end

  resources :follows

  resources :users do
      resources :follows
      resources :followers
      member do
        get :locate
      end
      
  end
  
  
  
  # resources :users do
  #     resources :groups
  # end
   
  resources :authentications
  resource :photo
  
  get "photo/new_photo_form"
  get "photo/new_photo_iframe"
  post "photo/set_image"

  root :controller => :welcome, :action => 'index'
  
  #this route should be last as it checks for the vanity urls
  get '/:vanity_name', :controller => 'vanities', :action => 'show'
  
  
end

tdd/app/views/shared/_bunchball_feed.html.erb
<tr class="<%= cycle("even", "odd") %>" >
	<% tag_type =  feed_item["tags"] 
	
		#look up information
		begin
			case tag_type
			when "GROUP_CREATE","GROUP_EDIT","GROUP_VISIT",GROUP_FOLLOW
				group = Group.find(feed_item["value"])
			when "USER_FOLLOW"
				user = User.find(feed_item["value"])
			end
		rescue %>
			<td></td></tr>
		<%
			return
		end
	
	   case  tag_type
	   when "GROUP_CREATE" %>
		<td>
			<a href="<%=group.get_group_profile_path%>">
				<%= image_tag Group.get_group_pic(group,"30_30")%>
			</a>
		</td>
		<td>
			<div class="feed_description">
				Created a new group called 
				<a href="<%=group.get_group_profile_path%>"><%=group.name%></a>
				<%if group.description.nil?%>.<%else%> that is described as "<%=group.description%>".<%end%>
			</div>
			<%= render :partial => 'shared/bunchball_feed_time', 
						:object=>Time.at(feed_item["ts"].to_i),
						:as=> :feed_time %>
		</td>
		
	   <% when "GROUP_EDIT" %>
			<td>
				<a href="<%=group.get_group_profile_path%>">
					<%= image_tag Group.get_group_pic(group,"30_30")%>
				</a>
			</td>
			<td>
				<div class="feed_description">
					Edited the group called 
					<a href="<%=group.get_group_profile_path%>"><%=group.name%></a>
					<%if group.description.nil?%>.<%else%> that is described as "<%=group.description%>".<%end%>
				
				</div>
				<%= render :partial => 'shared/bunchball_feed_time', 
							:object=>Time.at(feed_item["ts"].to_i),
							:as=> :feed_time %>
			</td>
		
	   <% when "GROUP_VISIT" %>
			<td>
				<a href="<%=group.get_group_profile_path%>">
					<%= image_tag Group.get_group_pic(group,"30_30")%>
				</a>
			</td>
			<td>
				<div class="feed_description">
					Entered the group <a href="<%=group.get_group_profile_path%>"><%=group.name%></a>.
				</div>
				<%= render :partial => 'shared/bunchball_feed_time', 
							:object=>Time.at(feed_item["ts"].to_i),
							:as=> :feed_time %>
			</td>
		
	   <% when "USER_FOLLOW" %>
			<td>
				<a href="<%=user.get_user_profile_path%>">
					<%= image_tag User.get_user_pic(user,"30_30")%>
				</a>
			</td>
			<td>
				<div class="feed_description">
					Started following <a href="<%=user.get_user_profile_path%>"><%=user.full_name%></a>.
				</div>
				<%= render :partial => 'shared/bunchball_feed_time', 
							:object=>Time.at(feed_item["ts"].to_i),
							:as=> :feed_time %>
			</td>
		
	   <% when "GROUP_FOLLOW" %>
			<td>
				<a href="<%=group.get_group_profile_path%>">
					<%= image_tag Group.get_group_pic(group,"30_30")%>
				</a>
			</td>
			<td>
				<div class="feed_description">
					Started following <a href="<%=group.get_group_profile_path%>"><%=group.name%></a>.
				</div>
				<%= render :partial => 'shared/bunchball_feed_time', 
							:object=>Time.at(feed_item["ts"].to_i),
							:as=> :feed_time %>
			</td>
		
	<% else %>
		<%#= feed_item.inspect %>
	<% end %>
	
</tr>

	

tdd/app/views/shared/_bunchball_feed_time.html.erb
<div class="feed_time">
	<%= time_ago_in_words(feed_time)%> ago
</div>

tdd/app/views/shared/_footer.html.erb
<div class="container clear" style="width:810px">
	<div class="span-20 clear small_font" style="margin-top:10px;border-top:1px solid #cccccc;width:810px">
			<hr class="space">
			<div class="span-7">
				Copyright 2010 vChatter, Inc.
			</div>
			<div class="span-14 last align_right">
				
				<%=link_to "About Us",  welcome_about_us_path %>
				&nbsp;|&nbsp; 
				<%=link_to "Jobs", welcome_jobs_path%>
				&nbsp;|&nbsp;
				<%=link_to "Press", welcome_press_path%>
				&nbsp;|&nbsp; 
				<%=link_to "Terms", welcome_terms_path%>
				&nbsp;|&nbsp; 
				<%=link_to "Privacy", welcome_privacy_path%>
				&nbsp;|&nbsp; 
				<%=link_to "Help", welcome_help_path%>

			</div>
	</div>

</div>
	
	
<!--flash-->
<div id="flash_notice_container" class="last bold_font align_center invisible" style="position:fixed;top:0;padding:10px;z-index:9999;width:100%"></div>
<% 	
	# two variables for readability during debugging
	  is_flash_content_present=false
	  flash_content=nil	
		flash_content= flash[:error] unless flash[:error].blank?
	    flash_content=flash[:notice] unless flash[:notice].blank? 
		flash_content=flash[:warn] unless flash[:warn].blank? 
		flash_content=flash[:alert] unless flash[:alert].blank? 

		is_flash_content_present=true unless flash_content.nil?
	  
if is_flash_content_present %>
	<script type="text/javascript">
		reportActionResult("<%= flash_content %>");
	</script>
<% end%>
<!-- end flash-->

<script type="text/javascript">

  //Facebook javascript
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());



  var uservoiceOptions = {
    key: 'vchatter',
    host: 'vchatter.uservoice.com', 
    forum: '99691',
    alignment: 'right',
    background_color:'#324387', 
    text_color: 'white',
    hover_color: '#E01B5D',
    lang: 'en',
    showTab: true
  };
  function _loadUserVoice() {
    var s = document.createElement('script');
    s.src = ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js";
    document.getElementsByTagName('head')[0].appendChild(s);
  }
  _loadSuper = window.onload;
  window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };
</script>

tdd/app/views/shared/_handle_signup.html.erb
<%=render_javascript_block do%>
	function handleClickRegisterFacebook(){
		window.open('<%= user_omniauth_authorize_path(:facebook) %>','','width=900,height=500');	
	}
	function handleClickRegisterTwitter(){
		window.open('<%=  user_omniauth_authorize_path(:twitter) %>','','width=900,height=500');	
	}	
<%end%>

<div id="secret_dialog_hider" class="invisible">
	<div id="email_signup_container_2" class="signup_content">
		
	</div>
	<div id="signup_container" class="signup_content">
	</div>

</div>

tdd/app/views/shared/_header.html.erb
<title>Fun and Free Video Groups</title>

<meta name="keywords" content="chat, video, flash, free, live, chatroom, chatline, service, software, voice, webcam, talk, friends, call, social, network, web 2.0, video chat, group video chat">
<meta name="description" content="vChatter is a fun, fast, and safe group video chat service that is free for everyone. Chat with your current friends on social networks or meet new friends who share your interests. Use it for personal and business needs. No downloads or installations so getting started on vChatter is quick and easy.">


<!-- todo - package js and css assets with asset_packeger-->
<script src="//cdn.optimizely.com/js/5679234.js"></script>
<%= stylesheet_link_tag 'screen', 
						'theme-start/jquery-ui-1.8.11.custom',
						'w3mg_standard',
						'w3mg_site_specific_public'
						%>
<%= javascript_include_tag 	'jquery-1.5.2.min'%>

<script type="text/javascript">
  var $j = jQuery.noConflict();
</script>
<%= javascript_include_tag 	:defaults,
							'jquery-ui-1.8.11.custom.min', 
							'jquery.form', 
							'W3MG_standard_utilities'
%>

<%= csrf_meta_tag %>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-16381078-5']);
    _gaq.push(['_setDomainName', '.vchatter.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

<%= yield :page_metadata %>

<%= yield :local_style_info %>

tdd/app/views/shared/_more_dialog.html.erb
 &nbsp; &nbsp;
<a href="javascript:handleClickMoreAboutVchatter();">
	<%=image_tag "sticky2_assets/welcome/qmark.png", {:style=>"margin-bottom:-3px;margin-left:-12px;"}%>
</a>

<div class="invisible">
	<div id="<%=more_id%>" title="Connecting to vChatter">
		<p>
			You'll follow your Facebook friends who are already on vChatter so that you can use all of vChatter's features. We won't message your friends who aren't on vChatter or post anything to your Facebook without your permission.
		</p>

		<p>
			For vChatter to be both a fun and trusted video chat destination, it's important that you use your real identity and connect your Facebook account with us. For questions please feel free to contact us at support@vchatter.com.
		</p>
		
		<div class="span-12 align_right">
			<a href="javascript:handleCloseMoreDialog<%=more_id%>()">Close</a>
		</div>	

	</div>
</div>

<%=render_javascript_block do%>

	function handleCloseMoreDialog<%=more_id%>(){$j('#<%=more_id%>').dialog('close')}

	function handleClickMoreAboutVchatter(){
		$j('#<%=more_id%>').dialog({width:500, show: 'fade', hide: 'puff', dialogClass: 'noTitleStuff'});
	}

<%end%>

tdd/app/views/shared/_oath_sites_javascripts.html.erb
<%
facebook_app_id=FACEBOOK_APP_ID
scope="email,user_birthday"
redirect_uri="http://vc_sandbox.local/facebook_registration?facebook=true"
%>

<div class="clearfix test_border">
	<a href="/auth/facebook" class="auth_provider">
	<%=image_tag "mockup_assets/dummy_facebook_connect.png", :style=>'border: 0px;'%>
	</a>
</div>
<br/>




<% 
=begin
	<% # THIS IS DEBUGGING CRUFT, SCOTT
	

<!--<a class="auth_provider" href="http://www.facebook.com/dialog/oauth/?scope=<%=scope%>&client_id=<%=FACEBOOK_APP_ID%>&redirect_uri=http://localhost:3000/registered_via_facebook/&response_type=token" target="_new"></a>-->


	%>
	<p><fb:login-button autologoutlink="true"></fb:login-button></p>
    <p><fb:like></fb:like></p>

    <div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({appId: 'FACEBOOK_APP_ID', status: true, cookie: true,
                 xfbml: true});
      };
      (function() {
        var e = document.createElement('script');
        e.type = 'text/javascript';
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        e.async = true;
        document.getElementById('fb-root').appendChild(e);
      }());
    </script>

	<div id="fb-root"></div>
	<script src="http://connect.facebook.net/en_US/all.js#appId=<%=FACEBOOK_APP_ID%>&xfbml=1"></script>

	<fb:registration 
	  fields="name,birthday,gender,location,email" 
	  redirect-uri="http://vc_sandbox.local/facebook_registration?facebook=true"
	  width="530">
	</fb:registration>
<%end%>	

<%

=begin

<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: 'your app id', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
=end

%>

tdd/app/views/shared/_popup_closer_script.html.erb
<%=render_javascript_block do%>
 // if an oath provider, like facebook opens this page, close it and set the parent
   if (window.opener){	
  
		if (window == parent) {
		   window.close();

		   window.opener.location = window.location.pathname
		}
  }
<%end%>

tdd/app/views/shared/_press_footer.html.erb
<hr class="space"/>
<hr class="space"/>
<hr class="space"/>
<hr class="space"/><hr class="space"/>
<hr class="space"/>
<!-- begin branding band - copied from existing site-->
<div class="span-24" id="brands">

   	  <span class="asseen">As seen on:</span> &nbsp;&nbsp;&nbsp;

      <a target="_blank" href="http://techcrunch.com/2010/09/21/vchatter-launches-a-pg-rated-version-of-chatroulette/"><img width="151" height="38" alt="TechCrunch" src="/images/press_coverage/tech-crunch.jpg"></a>

      <a target="_blank" href="http://www.fastcompany.com/1674711/chatroulette-comes-under-fire-vchatter-responds-with-family-safe-service"><img width="177" height="38" alt="FastCompany" src="/images/press_coverage/fast-company.jpg"></a>

      <a target="_blank" href="http://venturebeat.com/2010/09/21/vchatter-video-chat/"><img width="193" height="38" alt="Venturebeat" src="/images/press_coverage/venture-beat.jpg"></a>

      <a target="_blank" href="http://edition.cnn.com/2010/TECH/innovation/10/01/vchatter.facebook/"><img width="115" height="38" alt="CNN" src="/images/press_coverage/cnn.png"></a>
</div>
<!--end branding band-->

tdd/app/views/shared/_signed_in_navigation.html.erb
<table style="width:311px">
	<tr><!--need new image for left side-->
		<td  style="background-image:url(/images/sticky2_assets/groups/navbk_left.png);background-repeat:no-repeat;width:11px;height:39px;font-size:1px">
	
        </td>
		<td id="navigation_links" class="align_center">
			&nbsp;<%=link_to "Home", "/home/index"%>			
			&nbsp;&nbsp;<%= link_to "Profile", current_user.get_user_profile_path %>					          
  			&nbsp;&nbsp;<%= link_to "Browse", groups_path %>	
  			&nbsp;&nbsp;<%= link_to "Create Group", new_group_path %>	
			&nbsp;&nbsp;<%= link_to "Logout", destroy_user_session_path %>         
		</td>
		<td style="background-image:url(/images/sticky2_assets/groups/navbk_right.png);background-repeat:no-repeat;width:11px;height:39px;font-size:1px">&nbsp;										
		</td>	
	</tr>
</table>

tdd/app/views/shared/_signed_out_navigation.html.erb
<table style="width:311px">
	<tr><!--need new image for left side-->
		<td id="signedOutNavLeft">
			&nbsp;
        </td>
		<td id="navigation_links" class="align_center">
			&nbsp;<%=link_to "Home", root_path %>			
  			&nbsp;&nbsp;<%= link_to "Browse", groups_path %>	
  			&nbsp;&nbsp;<%= link_to_function "Sign In", "signIn();", :id=> "signInLink" %>	
			&nbsp;&nbsp;<%= link_to_function "Sign Up", "signUp();", :id=> "signUpLink" %>         
		</td>
		<td id="signedOutNavRight">
			&nbsp;										
		</td>	
	</tr>
</table>


<div id="signInDialog">
	<table>
		<tr>
			<td>
				<div id="signInDialogLeft"></div>
			</td>
			<td>
				<div id="signInDialogMid">
					<div>
						<%= form_for(User.new, :as => 'user', :url => session_path('user')) do |f| %>
							<table>
								<tr>
									<td>Email:</td>
									<td colspan="2">
										<%= f.text_field :email, 
													:style=>"background-color: white",
													:id=>"dialogEmail" %>
									</td>
								</tr>
								<tr>
									<td>Password:</td>
									<td colspan="2">
										<%= f.password_field :password, :id=>"dialogPassword" %>
									</td>
								</tr>
								<tr>
									<td></td>
									<td >
										<div id="rememberMeDiv">
											<table>
												<tr>
													<td>
														<%= f.check_box :remember_me %> 
														Keep me logged in
													</td>
												</tr>
												<tr>
													<td>
														<a href="<%= new_user_password_path %>">Forgot password?</a>
													</td>
												</tr>
											</table>
											
										</div>
									</td>
									<td>
										<%= f.submit "", :id=>"signInButton" %>
									</td>
								</tr>
							</table>
						
						<% end %>
					</div>
				</div>
			</td>
			<td>
				<div id="signInDialogRight"></div>
			</td>
		</tr>
	</table>
</div>

<div id="signUpDialog">
	<table>
		<tr>
			<td>
				<div id="signUpDialogLeft"></div>
			</td>
			<td>
				<div id="signUpDialogMid">
					<div>
						<table>
							<tr>
								<td>
									<div style="font-size: 11px;">
										Create Account Using:
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div style="padding-top:4px;">
										<%= button_to_function "&nbsp;", 
										"handleClickRegisterFacebook();", 
										:id=>"facebookSignupButton" %>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div style="padding-top: 5px;font-family: Arial;font-weight: bold;">
										The fastest way to sign in
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div style="padding-top: 10px;">
										Or with 
										<a href="javascript:handleClickRegisterTwitter()">
											Twitter
										</a> or 
										<a href="javascript:handleClickSignUpEmail()">
											Email
										</a>
									</div>
								</td>
							</tr>
						</table>
						
					</div>
				</div>
			</td>
			<td>
				<div id="signUpDialogRight"></div>
			</td>
		</tr>
	</table>
</div>

<script>
	$j(document).ready( function() {
		
		var signinLink = $j('#signInLink')
		var signInPos = signinLink.offset();
		var signInMid = signInPos.left + (signinLink.width() / 2)
		var dialogWidth = 260;
		 
		
		$j('#signInDialog').dialog({ 
			autoOpen: false,
			width: dialogWidth + 'px',
			show: 'fade',
			hide: 'puff',
			position: [signInMid - (dialogWidth / 2 ), (signInPos.top + signinLink.height() + 2) ],
			dialogClass: "signInDialog",
			resizable: false
		});
		
		var signUpLink = $j('#signUpLink')
		var signUpPos = signUpLink.offset();
		console.dir(signUpPos);
		var signUpMid = signUpPos.left + (signUpLink.width() / 2)
		console.dir(signUpMid);
		dialogWidth = 150;
		 
		
		$j('#signUpDialog').dialog({ 
			autoOpen: false,
			width: dialogWidth + 'px',
			show: 'fade',
			hide: 'puff',
			position: [signUpMid - (dialogWidth / 2 ), (signUpPos.top + signUpLink.height() + 2) ],
			dialogClass: "signUpDialog",
			resizable: false
		});
	});
	
	function signIn() {
		$j('#signInDialog').dialog('open');
	}
	
	function signUp() {
		$j('#signUpDialog').dialog('open');
	}
</script>
<%=render(:partial=>"shared/handle_signup")%>	

tdd/app/views/shared/_signup_form_hider.html.erb
<div id="signup_form_displayer" class="invisible">
      <%=render(:partial=>"shared/user_new_html")%>
</div>	

tdd/app/views/shared/_window_children_plugin.html.erb
/**
 * Opener Helper Plugin
 *
 * This plugin support to manage window.opener object.
 *
 * Copyright (c) 2011 W3MG
 * Dual licensed under the MIT or GPL Version 2 licenses.
 *
 * Author: Brian
 * Date: Mar 29 2011
 */

/**
 * @name propChildUrl2Opener
 * @purpose This function make the opener window will be redirected to child window's url, and close child window.
 * @params url(String) if null, just redirect to child's url, if not, redirect to the url given.
 * @example window.propChildUrl2Opener(), or window.propChildUrl2Opener({'url': 'http://www.google.com'})
 * @return null 
 */ 
;(function(win) {
	win.propChildUrl2Opener = function(options) {
		// Merge passed options with defaults
		var opts = mergeParameters(win.propChildUrl2Opener.defaults, options);
		
		if (win.opener != null ) {
			if (opts.popupfunction != null) {
				win.opener[opts.popupfunction]();
			} else if (opts.url != null) {
				win.opener.location.href = opts.url;
			}
			win.close();
		}
		return null;
	};

	function mergeParameters(first_obj, second_obj){
		var result = {};
		for (attrname in first_obj) { result[attrname] = first_obj[attrname]; }
		for (attrname in second_obj) { result[attrname] = second_obj[attrname]; }
		return result;
	}

	// Default options
	win.propChildUrl2Opener.defaults = {
		'url': win.location.href
	};
})(window);

tdd/app/views/shared/_window_children_plugin2.html.erb
/**
 * Opener Helper Plugin
 *
 * This plugin support to manage window.opener object.
 *
 * Copyright (c) 2011 W3MG
 * Dual licensed under the MIT or GPL Version 2 licenses.
 *
 * Author: Brian
 * Date: Mar 29 2011
 */

/**
 * @name propChildUrl2Opener
 * @purpose This function make the opener window will be redirected to child window's url, and close child window.
 * @params url(String) if null, just redirect to child's url, if not, redirect to the url given.
 * @example window.propChildUrl2Opener(), or window.propChildUrl2Opener({'url': 'http://www.google.com'})
 * @return null 
 */ 
;(function(win) {
	win.propChildUrl2Opener = function(options) {
		// Merge passed options with defaults
		var opts = mergeParameters(win.propChildUrl2Opener.defaults, options);
		
		if (win.opener != null) {
			win.opener.location.href = opts.url;
			win.close();
		}
		return null;
	};

	function mergeParameters(first_obj, second_obj){
		var result = {};
		for (attrname in first_obj) { result[attrname] = first_obj[attrname]; }
		for (attrname in second_obj) { result[attrname] = second_obj[attrname]; }
		return result;
	}

	// Default options
	win.propChildUrl2Opener.defaults = {
		'url': win.location.href
	};
})(window);